"""empty message

Revision ID: 50f2401f491f
Revises: 1ffd22edc14b
Create Date: 2020-05-08 21:24:03.548540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50f2401f491f'
down_revision = '1ffd22edc14b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('review_content', sa.String(length=1000), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'review_content')
    # ### end Alembic commands ###
